#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path('../../lib', __FILE__)

require 'wick/io'

Wick::IO.bind(read: $stdin, write: $stdout) do |input|
  initial = {total: 0}

  state = input.scan(initial) { |s, line|
    if line.strip.empty?
      {total: 0, message: "Total: #{s[:total]}"}
    else
      {total: s[:total] + line.to_f}
    end
  }
  
  output = state.select { |s| s.has_key?(:message) }
                .map    { |s| s[:message] + "\n\n" }

  output
end
