#!/usr/bin/env ruby
# encoding: utf-8

$LOAD_PATH << File.expand_path('../../lib', __FILE__)

require 'wick/io'

Wick::IO.bind(read: $stdin, write: $stdout) do |input|
  input.map { |line| "Haha! You said “#{line.chomp}”." }
end
