#!/usr/bin/env ruby
# encoding: utf-8

$LOAD_PATH << File.expand_path('../../lib', __FILE__)

require 'wick/io'

Wick::IO.listen!($stdin, $stdout) do |input|
  input.skip_start.map { |line| "Haha! You said “#{line.chomp}”." }
end
