#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path('../../lib', __FILE__)

require 'wick/io'

Wick::IO.bind(read: $stdin, write: $stdout) do |input|
  initial = {
    total: 0,
    message: "Type one number per line. Enter a blank line to calculate total and reset."
  }

  input
    .scan(initial) { |state, line|
      if line.strip.empty?
        {message: "Total: #{state[:total]}", total: 0}
      else
        {total: state[:total] + line.to_f}
      end
    }
    .select { |state| state.has_key?(:message) }
    .map    { |state| state[:message] + "\n\n" }
end
